### ISSUE TITLE
Adding RTS5260 Support

### ISSUE THREAD

**Issue by lulujyc** [0xFireWolf/RealtekCardReader#3]
Hi FireWolf:

First of all, thank you very much for implementing the Realtek SD card driver. I'm testing it on a Dell Precision 7530, which has the RTS5260 chip (10EC, 5260). I used the RTS525A class to experiment, however, it is not supported and recognized at all. I wonder if there is something I could do to help you implement the driver. The chip is most commonly found on Dell business laptops. Thank you again!

**Comment by 0xFireWolf** [comment]
> I used the RTS525A class to experiment, however, it is not supported and recognized at all.

This is expected, because each controller class contains chip-specific code that may not be compatible for other chips.

Try the attached driver and see if your chip can be recognized and work properly.

[RealtekCardReader_0.9.6p1_f2b10c6_DEBUG.zip](https://github.com/0xFireWolf/RealtekCardReader/files/6829339/RealtekCardReader_0.9.6p1_f2b10c6_DEBUG.zip)

**Comment by lulujyc** [comment]
Thank you so much! The card reader worked well on Monterey, with your build and RealtekCardReaderFriend.

<img width="481" alt="图片" src="https://user-images.githubusercontent.com/32395067/126032451-c48ece1b-e6c8-482b-b6e8-8fe67b093de9.png">

**Comment by 0xFireWolf** [comment]
Does the SD card work properly as well? What's the read and write speed under macOS and other systems like Windows?

**Comment by lulujyc** [comment]
Yes, it is correctly recognized and has moderate writing speeds, as I only have an SDHC card to test. Sorry I don't have any UHS cards to report the maximum speed of the driver.
